// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractionState } from "./ExtractionState";

export type ExtractionStatus = { state: ExtractionState, progress: number, currentFile: string | null, error: string | null, };
