// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MusicTrack = { id: string, title: string, filePath: string, durationSecs: number, };
