// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaybackStatus = { isPlaying: boolean, isPaused: boolean, currentSoundId: string | null, positionSecs: number, durationSecs: number, volume: number, sampleRate: number, bitrateKbps: number, };
