// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Sound = { id: string, eventName: string, displayName: string, category: string, unitType: string | null, subcategory: string, duration: number, filePath: string, tags: Array<string>, };
